sudo: required

language: generic

services:
  - docker

script: >
  docker run
  -it
  -v $PWD:/jekyll
  -e TRAVIS=true
  -e GIT_NAME="$GIT_NAME"
  -e GIT_EMAIL="$GIT_EMAIL"
  -e GH_TOKEN="$GH_TOKEN"
  zburgermeiszter/blog-build:latest
  site:deploy

