sudo: required

language: ruby

services:
  - docker

script: >
  docker run
  -it
  -v $PWD:/jekyll
  -e TRAVIS=true
  -e GIT_NAME="$GIT_NAME"
  -e GIT_EMAIL="$GIT_EMAIL"
  -e GH_TOKEN="$GH_TOKEN"
  zburgermeiszter/blog-build:latest
  site:deploy

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
branches:
  only:
    - master

