# Jykell configuration
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
highlighter: rouge
paginate: 5
language: 'en-uk'

# Website info
name: 'Finding The Way Home'
description: "A beautiful narrative written with the world's most elegant publishing platform. The story begins here."

# Author's info
author: 'Casper McFadden'
# edit 'categories' in the front matter of every post to match this username
nickname: casper
bio: 'A paranormal expert and his daughter bunk in an abandoned house populated by 3 mischievous ghosts and one friendly one.'
location: 'Maine, USA'
url: 'https://blog.burgermeiszter.com'
image: 'assets/images/casper.png'

short_url: 'blog.burgermeiszter.com'
google_analytics: UA-70076814-2
disqus: burgermeisztercom
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: 

# Permalinks
# permalink: /:title
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag
# permalink: /:categories/:year/:month/:day/:title.html


# gems and other configs
gems: [jekyll-paginate, jekyll-time-to-read]
exclude: [vendor]
include: ["_pages"]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...

# Front Matter defaults (http://jekyllrb.com/docs/configuration/#front-matter-defaults)
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      description: ''
      class: 'page-template'
      navigation: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: 'zburgermeiszter'
      description: ''
      class: 'post-template'
      navigation: true
      disqus: true

# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: false
lsi: false
username: zburgermeiszter
repo: blog.burgermeiszter.com
branch: master
posts_branch: posts
relative_source: ../source/
destination: _site
production_url:  https://blog.burgermeiszter.com/
source_url:      https://github.com/zburgermeiszter/blog/

exclude:
  - README.md
  - Dockerfile
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
