source "https://rubygems.org"

gem "json"
gem "jekyll"
#, "~> 3.2.1"
gem "io-console"
#, "~>0.4.6"
#gem "rdiscount", "~> 2.1.7"
#gem "pygments.rb", "~> 0.6.3"
#gem 'kramdown', '~> 1.8'
gem "rouge"
#, "~> 2.0.5"
gem "github-pages"
#, "~> 93"
gem "rake"
#, "~> 10.1.1"
gem "jekyll-watch"
#,"~> 1.1"

gem "jekyll-sass-converter","1.3.0"
